version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "michaeloboyle"
    assignees:
      - "michaeloboyle"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    labels:
      - "dependencies"
      - "python"

  # Node.js dependencies (for UI)
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "michaeloboyle"
    assignees:
      - "michaeloboyle"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    labels:
      - "dependencies"
      - "ui"
      - "javascript"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "michaeloboyle"
    assignees:
      - "michaeloboyle"
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "michaeloboyle"
    assignees:
      - "michaeloboyle"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"